[package]
authors = ["Michael Daffin <michael@daffin.io>"]
name = "scribe"
version = "0.1.0"

[dependencies]
failure = "0.1.1"
failure_derive = "0.1.1"
structopt = "0.2.10"
human-panic = "1.0.0"
termion = "1.5.1"
log = "0.4.2"
simplelog = "0.5.2"
itertools = "0.7.8"
